#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

while IFS=':' read -r username password uid gid info home shell; do
  echo "Username: $username"
  echo "User ID: $uid"
  echo "Home directory: $home"
done < "/etc/passwd"

