#!/usr/bin/env bash
#-------
# Tells a story based on the contents of the `/etc/passwd` file.
#-------
filename="/etc/passwd"
IFS=:
while read -r user pass uid gid info home shell
do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $info"
done < "$filename"
